### ISSUE TITLE
Add example of type-checking screens

### ISSUE THREAD

**Issue by karlhorky** [ramonh/expo-lesson-feb-2022#3]
Hi @hola-soy-milk, thanks for the amazing session!

It seems like Expo Router is build on React Navigation: https://github.com/expo/router/issues/103

So probably this page is indeed the docs for adding the correct types: https://reactnavigation.org/docs/typescript/#type-checking-screens

**Comment by hola-soy-milk** [comment]
Should be [fixed using custom types](https://github.com/hola-soy-milk/react-native-expo/blob/main/finished-app/app/newPost.tsx#L15)

If this looks good, can we close it?

**Comment by karlhorky** [comment]
Typing them manually probably won't work really well for upgrades (or if another prop such as `route` is added)

I guess using the types from `react-navigation` is the right way to go. Here's an example of a screen in an app using `react-navigation` (also closer to what is in the docs):

https://github.com/react-navigation/react-navigation/blob/d7032ba8bb6ae24030a47f0724b61b561132fca6/example/src/Screens/NativeStack.tsx#L15-L26

**Comment by hola-soy-milk** [comment]
Thanks for this, Karl!

[Should be now using navigation typing properly](https://github.com/hola-soy-milk/react-native-expo/blob/main/finished-app/app/newPost.tsx#L22).

What do you think?

**Comment by karlhorky** [comment]
Ok, looks like it was almost correct. Seems like this was the correct version:

```diff
type NativeStackParams = {
-  index: {post: Post}
+  index: {post?: Post} | undefined;
};
```

I've made the changes in #7
